<package format="3">
    <name>adaptive_bridge</name>
    <version>0.1.0</version>
    <description>Adaptive Bridge: dynamic topic decoupling and QoS adaptation</description>
    <maintainer email="kaushalrajpuwar@protonmail.com">Kaushalraj Puwar</maintainer>
    <license>Apache-2.0</license>

    <depend>rclpy</depend>
    <depend>sensor_msgs</depend>

    <buildtool_depend>ament_python</buildtool_depend>

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>
    <test_depend>python3-pytest</test_depend>
    
    <exec_depend>python3-yaml</exec_depend>

    <export>
        <build_type>ament_python</build_type>
    </export>
</package>
